### ISSUE TITLE
Start to reorganize repo into Python module

### ISSUE THREAD

**Issue by lintool** [gwf-uwaterloo/waterwheel#10]
We can use this as a guide: https://github.com/castorini/pyserini/

**Comment by lintool** [comment]
Ref #12 

I think the API we want is something like:

```python
from waterwheel import WaterWheel
ner = WaterWheel(...)
doc = nlp(...)
```

So our code behaves just like any other spaCy module?

https://spacy.io/api/entityrecognizer

**Comment by nikhilro** [comment]
from slack discussion:
tensorflow would be a good starting point to base our `__init__` use to "flatten" the api and bring some nested classes higher up. [link](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/__init__.py)

**Comment by lintool** [comment]
Initial goals achieved for now. Closing.
