### ISSUE TITLE
WaterWheel takes nlp in constructor... why?

### ISSUE THREAD

**Issue by lintool** [gwf-uwaterloo/waterwheel#18]
According to the current `WaterWheel` constructor, it seems to take an `nlp` object:
https://github.com/gwf-uwaterloo/waterwheel/blob/master/waterwheel/waterwheel.py#L24

But doesn't seem to do anything with it... Except for this line:
https://github.com/gwf-uwaterloo/waterwheel/blob/master/waterwheel/waterwheel.py#L157

Can you explain what's going on?

**Comment by Govind9** [comment]
The `nlp` object is also used by `EntityRuler` class inherited by `WaterWheel`. It is required to initialize the `PhraseMatcher` and general `Matcher` attributes which are then used to find the matches:
https://github.com/explosion/spaCy/blob/master/spacy/pipeline/entityruler.py#L35

**Comment by lintool** [comment]
Ah, I see, thanks for the explanation.
